//
// Created by samed on 23.10.18.
//

#ifndef DATACRAWLER_PROJECT_DATAMODULESENUM_H
#define DATACRAWLER_PROJECT_DATAMODULESENUM_H


enum DataModulesEnum {
    SCREENSHOT_MODULE = 0,
    URL_MODULE = 1
};


#endif //DATACRAWLER_PROJECT_DATAMODULESENUM_H
