apiVersion: batch/v1
kind: Job
metadata:
  name: datacrawler-job
spec:
  parallelism: 38
  template:
    metadata:
      labels:
        name: datacrawler
    spec:
      containers:
      - name: datacrawler
        image: gcr.io/nips-2018-102018/datacrawler:latest
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: datacrawler-output
          mountPath: /opt/apt/output
      restartPolicy: OnFailure
      volumes:
      - name: datacrawler-output
        persistentVolumeClaim:
           claimName: datacrawler-output-claim
